output "control_instance_id" { value = oci_core_instance.control.id }
output "control_public_ip" { value = oci_core_instance.control.public_ip }
output "control_private_ip" { value = oci_core_instance.control.private_ip }
output "coolify_setup_url" { value = "http://${oci_core_instance.control.public_ip}:8000" }
output "game_node_enabled" { value = var.enable_game_node }
output "game_public_ip" { value = var.enable_game_node ? oci_core_instance.game[0].public_ip : null }
output "game_private_ip" { value = var.enable_game_node ? oci_core_instance.game[0].private_ip : null }
output "game_connect_hint" { value = var.enable_game_node ? "${oci_core_instance.game[0].public_ip}:${var.game_udp_port}" : null }
output "cost_warning" { value = var.enable_game_node ? "x86 Unreal node enabled: verify OCI pricing before Apply." : "x86 Unreal node disabled." }
output "tgg_candidate_sha" { value = lower(var.candidate_sha) }
output "next_step" { value = "Finish Coolify setup, configure HTTPS, install the repo-native TGG Host Agent, then run npm run check:tgg-live-readiness." }
